### ISSUE TITLE
401 Client error "Not authorized"

### ISSUE THREAD

**Issue by jstavel** [edeposit/cz-urnnbn-api#22]
urnnbn = urnnbn_api.register_document_obj(urnnbn_api.MonographComposer(title=self.context.title, author="", format="pdf"))

**Comment by jstavel** [comment]
*** HTTPError: 401 Client Error: Unauthorized
<html><head><title>Apache Tomcat/7.0.26 - Error report</title><style></style> </head><body><h1>HTTP Status 401 - Bad Credentials</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>m\
essage</b> <u>Bad Credentials</u></p><p><b>description</b> <u>This request requires HTTP authentication (Bad Credentials).</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>

**Comment by Bystroushaak** [comment]
I've sent you the password.

**Comment by jstavel** [comment]
If you send me the password to mobile I cannot read it. More than 4days I have not got mobile. I lost it I do not know where. :-)

**Comment by Bystroushaak** [comment]
Nope, email.

**Comment by jstavel** [comment]
Thanks.
